services:
  db:
    image: postgres:16.2-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: wisho
      POSTGRES_PASSWORD: wisho
      POSTGRES_DB: wisho_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: