[project]
name = "wisho"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Massimo Meert", email = "pro@masmeert.com" }
]
requires-python = ">=3.13"
dependencies = [
    "pydantic>=2.12.3",
]

[project.scripts]
wisho = "wisho:main"

[build-system]
requires = ["uv_build>=0.9.5,<0.10.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest>=8.4.2",
]
