from enum import Enum


class SubjectField(str, Enum):
    """JMdict subject field indicators - specialized domain vocabulary"""

    BUDDHISM = "Buddh"
    CHEMISTRY = "chem"
    COMPUTING = "comp"
    ECONOMICS = "econ"
    MEDICINE = "med"
    MUSIC = "music"
    PHYSICS = "physics"
    SPORTS = "sports"
    ANATOMY = "anat"
    ARCHITECTURE = "archit"
    ASTRONOMY = "astron"
    BIOLOGY = "biol"
    BOTANY = "bot"
    BUSINESS = "bus"
    ENGINEERING = "engr"
    FINANCE = "finc"
    FOOD = "food"
    GEOMETRY = "geom"
    GEOLOGY = "geol"
    LAW = "law"
    LINGUISTICS = "ling"
    MATHEMATICS = "math"
    MILITARY = "mil"
    PHILOSOPHY = "phil"
    PSYCHOLOGY = "psych"
    SHINTO = "Shinto"
    ZOOLOGY = "zool"
    BASEBALL = "baseb"
    MAHJONG = "mahj"
    SHOGI = "shogi"
    SUMO = "sumo"
    MARTIAL_ARTS = "MA"
