from enum import Enum


class KanjiInformation(str, Enum):
    """JMDict-style flags describing kanji-specific quirks."""

    ATEJI = "ateji"  # ateji (phonetic) reading
    IRREGULAR_KANJI = "iK"  # irregular kanji usage
    IRREGULAR_KANA = "ik"  # irregular kana usage
    IRREGULAR_OKURIGANA = "io"  # irregular okurigana
    OUTDATED_KANJI = "oK"  # out-dated kanji
    RARELY_USED_KANJI = "rK"  # rarely used kanji form
    SEARCH_ONLY_KANJI = "sK"  # search-only kanji form


class ReadingInformation(str, Enum):
    """JMDict-style flags describing reading-specific quirks."""

    GIKUN = "gikun"  # gikun/jukujikun reading
    IRREGULAR_KANA = "ik"  # irregular kana usage
    OUTDATED_KANA = "ok"  # obsolete kana usage
    RARELY_USED_KANA = "rk"  # rarely used kana form
    SEARCH_ONLY_KANA = "sk"  # search-only kana form


class PartOfSpeech(str, Enum):
    """JMDict part-of-speech tags."""

    ADJECTIVE_F = "adj-f"  # noun/verb acting prenominally
    ADJECTIVE_I = "adj-i"
    ADJECTIVE_IX = "adj-ix"  # yoi/ii class
    ADJECTIVE_KU = "adj-ku"  # archaic
    ADJECTIVE_NA = "adj-na"
    ADJECTIVE_NARI = "adj-nari"  # archaic/formal
    ADJECTIVE_NO = "adj-no"  # genitive 'no' nouns
    ADJECTIVE_PN = "adj-pn"  # rentaishi
    ADJECTIVE_SHIKU = "adj-shiku"  # archaic
    ADJECTIVE_T = "adj-t"  # taru-adjective
    ADVERB = "adv"
    ADVERB_TO = "adv-to"
    AUXILIARY = "aux"
    AUXILIARY_ADJECTIVE = "aux-adj"
    AUXILIARY_VERB = "aux-v"
    CONJUNCTION = "conj"
    COPULA = "cop"
    COUNTER = "ctr"
    EXPRESSION = "exp"
    INTERJECTION = "int"
    NOUN = "n"
    NOUN_PREFIX = "n-pref"
    NOUN_SUFFIX = "n-suf"
    NUMERIC = "num"
    PRONOUN = "pn"
    PREFIX = "pref"
    PARTICLE = "prt"
    SUFFIX = "suf"
    UNCLASSIFIED = "unc"
    VERB_ICHIDAN = "v1"
    VERB_ICHIDAN_KURERU = "v1-s"
    VERB_NIDAN_U_LOWER = "v2a-s"
    VERB_NIDAN_BU_UPPER = "v2b-k"
    VERB_NIDAN_DZU_LOWER = "v2d-s"
    VERB_NIDAN_GU_LOWER = "v2g-s"
    VERB_NIDAN_GU_UPPER = "v2g-k"
    VERB_NIDAN_HU_LOWER = "v2h-s"
    VERB_NIDAN_HU_UPPER = "v2h-k"
    VERB_NIDAN_KU_LOWER = "v2k-s"
    VERB_NIDAN_KU_UPPER = "v2k-k"
    VERB_NIDAN_MU_LOWER = "v2m-s"
    VERB_NIDAN_NU_LOWER = "v2n-s"
    VERB_NIDAN_RU_LOWER = "v2r-s"
    VERB_NIDAN_RU_UPPER = "v2r-k"
    VERB_NIDAN_SU_LOWER = "v2s-s"
    VERB_NIDAN_TSU_LOWER = "v2t-s"
    VERB_NIDAN_TSU_UPPER = "v2t-k"
    VERB_NIDAN_U_WE = "v2w-s"
    VERB_NIDAN_YU_LOWER = "v2y-s"
    VERB_NIDAN_YU_UPPER = "v2y-k"
    VERB_NIDAN_ZU_LOWER = "v2z-s"
    VERB_YODAN_BU = "v4b"
    VERB_YODAN_GU = "v4g"
    VERB_YODAN_HU = "v4h"
    VERB_YODAN_KU = "v4k"
    VERB_YODAN_MU = "v4m"
    VERB_YODAN_RU = "v4r"
    VERB_YODAN_SU = "v4s"
    VERB_YODAN_TSU = "v4t"
    VERB_GODAN_ARU = "v5aru"
    VERB_GODAN_BU = "v5b"
    VERB_GODAN_GU = "v5g"
    VERB_GODAN_KU = "v5k"
    VERB_GODAN_IKU = "v5k-s"
    VERB_GODAN_MU = "v5m"
    VERB_GODAN_NU = "v5n"
    VERB_GODAN_RU = "v5r"
    VERB_GODAN_RU_IRREGULAR = "v5r-i"
    VERB_GODAN_SU = "v5s"
    VERB_GODAN_TSU = "v5t"
    VERB_GODAN_U = "v5u"
    VERB_GODAN_U_SPECIAL = "v5u-s"
    VERB_INTRANSITIVE = "vi"
    VERB_KURU = "vk"
    VERB_NU_IRREGULAR = "vn"
    VERB_RU_IRREGULAR = "vr"
    VERB_SURU = "vs"
    VERB_SU_PRECURSOR = "vs-c"
    VERB_SURU_IRREGULAR = "vs-i"
    VERB_SURU_SPECIAL = "vs-s"
    VERB_TRANSITIVE = "vt"
    VERB_ZURU = "vz"


class MiscInformation(str, Enum):
    """Usage/register flags not covered by POS or fields."""

    ABBREVIATION = "abbr"
    ARCHAIC = "arch"
    CHARACTER = "char"
    CHILDRENS_LANGUAGE = "chn"
    COLLOQUIAL = "col"
    COMPANY_NAME = "company"
    CREATURE = "creat"
    DATED = "dated"
    DEITY = "dei"
    DEROGATORY = "derog"
    DOCUMENT = "doc"
    EUPHEMISTIC = "euph"
    EVENT = "ev"
    FAMILIAR_LANGUAGE = "fam"
    FEMALE_TERM = "fem"
    FICTION = "fict"
    FORMAL = "form"
    GIVEN_NAME = "given"
    GROUP = "group"
    HISTORICAL = "hist"
    HONORIFIC = "hon"
    HUMBLE = "hum"
    IDIOMATIC = "id"
    JOCULAR = "joc"
    LEGEND = "leg"
    MANGA_SLANG = "m-sl"
    MALE_TERM = "male"
    MYTHOLOGY = "myth"
    INTERNET_SLANG = "net-sl"
    OBJECT = "obj"
    OBSOLETE = "obs"
    ONOMATOPOEIA = "on-mim"
    ORGANIZATION_NAME = "organization"
    PERSON_NAME = "person"
    PLACE_NAME = "place"
    POETICAL = "poet"
    POLITE = "pol"
    PRODUCT_NAME = "product"
    PROVERB = "proverb"
    QUOTATION = "quote"
    RARE = "rare"
    SENSITIVE = "sens"
    SERVICE = "serv"
    SHIP_NAME = "ship"
    SLANG = "sl"
    SURNAME = "surname"
    USUALLY_KANA = "uk"
    UNCLASSIFIED_NAME = "unclass"
    VULGAR = "vulg"
    WORK_OF_ART = "work"
    YOJIJUKUGO = "yoji"


class SubjectField(str, Enum):
    """Domain/subject labels."""

    BUDDHISM = "Buddh"
    CHRISTIANITY = "Christn"
    MARTIAL_ARTS = "MA"
    SHINTO = "Shinto"
    AGRICULTURE = "agric"
    ANATOMY = "anat"
    ARCHEOLOGY = "archeol"
    ARCHITECTURE = "archit"
    ART = "art"
    ASTRONOMY = "astron"
    AUDIOVISUAL = "audvid"
    AVIATION = "aviat"
    BASEBALL = "baseb"
    BIOCHEMISTRY = "biochem"
    BIOLOGY = "biol"
    BOTANY = "bot"
    BOXING = "boxing"
    BUSINESS = "bus"
    CARD_GAMES = "cards"
    CHEMISTRY = "chem"
    CHINESE_MYTHOLOGY = "chmyth"
    CIVIL_ENGINEERING = "civeng"
    CLOTHING = "cloth"
    COMPUTING = "comp"
    CRYSTALLOGRAPHY = "cryst"
    DENTISTRY = "dent"
    ECOLOGY = "ecol"
    ECONOMICS = "econ"
    ELECTRICITY = "elec"
    ELECTRONICS = "electr"
    EMBRYOLOGY = "embryo"
    ENGINEERING = "engr"
    ENTOMOLOGY = "ent"
    FIGURE_SKATING = "figskt"
    FILM = "film"
    FINANCE = "finc"
    FISHING = "fish"
    FOOD = "food"
    GARDENING = "gardn"
    GENETICS = "genet"
    GEOGRAPHY = "geogr"
    GEOLOGY = "geol"
    GEOMETRY = "geom"
    GO_GAME = "go"
    GOLF = "golf"
    GRAMMAR = "gramm"
    GREEK_MYTHOLOGY = "grmyth"
    HANAFUDA = "hanaf"
    HORSE_RACING = "horse"
    INTERNET = "internet"
    JAPANESE_MYTHOLOGY = "jpmyth"
    KABUKI = "kabuki"
    LAW = "law"
    LINGUISTICS = "ling"
    LOGIC = "logic"
    MAHJONG = "mahj"
    MANGA = "manga"
    MATHEMATICS = "math"
    MECHANICAL_ENGINEERING = "mech"
    MEDICINE = "med"
    METEOROLOGY = "met"
    MILITARY = "mil"
    MINERALOGY = "min"
    MINING = "mining"
    MOTORSPORT = "motor"
    MUSIC = "music"
    NOH = "noh"
    ORNITHOLOGY = "ornith"
    PALEONTOLOGY = "paleo"
    PATHOLOGY = "pathol"
    PHARMACY = "pharm"
    PHILOSOPHY = "phil"
    PHOTOGRAPHY = "photo"
    PHYSICS = "physics"
    PHYSIOLOGY = "physiol"
    POLITICS = "politics"
    PRINTING = "print"
    PROFESSIONAL_WRESTLING = "prowres"
    PSYCHIATRY = "psy"
    PSYCHOANALYSIS = "psyanal"
    PSYCHOLOGY = "psych"
    RAILWAY = "rail"
    ROMAN_MYTHOLOGY = "rommyth"
    SHOGI = "shogi"
    SKIING = "ski"
    SPORTS = "sports"
    STATISTICS = "stat"
    STOCK_MARKET = "stockm"
    SUMO = "sumo"
    SURGERY = "surg"
    TELECOMMUNICATIONS = "telec"
    TRADEMARK = "tradem"
    TELEVISION = "tv"
    VETERINARY = "vet"
    VIDEO_GAMES = "vidg"
    ZOOLOGY = "zool"


class Dialect(str, Enum):
    """Regional/dialect tags."""

    BRAZILIAN = "bra"
    HOKKAIDO_BEN = "hob"
    KANSAI_BEN = "ksb"
    KANTOU_BEN = "ktb"
    KYOTO_BEN = "kyb"
    KYUUSHUU_BEN = "kyu"
    NAGANO_BEN = "nab"
    OSAKA_BEN = "osb"
    RYUUKYUU_BEN = "rkb"
    TOUHOKU_BEN = "thb"
    TOSA_BEN = "tsb"
    TSUGARU_BEN = "tsug"


class GlossType(str, Enum):
    """Role of a gloss within a sense."""

    LITERAL = "literal"
    FIGURATIVE = "figurative"
    EXPLANATION = "explanation"
    TRADEMARK = "trademark"
