name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: python
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"

      - name: Install uv
        uses: astral-sh/setup-uv@v5
      
      - name: Install the project
        run: uv sync --locked --all-extras --dev

      - name: Lint with Ruff
        run: uv run ruff check .

      - name: Run tests
        run: uv run pytest tests